In [1]:
# Zepto SQL project

# EDA

In [2]:
import pandas as pd

df = pd.read_csv("../data/zepto_raw.csv",encoding='cp1252')

df.head()

,Category,name,mrp,discountPercent,availableQuantity,discountedSellingPrice,weightInGms,outOfStock,quantity
0,Fruits & Vegetables,Onion,2500,16,3,2100,1000,False,1
1,Fruits & Vegetables,Tomato Hybrid,4200,16,3,3500,1000,False,1
2,Fruits & Vegetables,Tender Coconut,5100,15,3,4300,58,False,1
3,Fruits & Vegetables,Coriander Leaves,2000,15,3,1700,100,False,100
4,Fruits & Vegetables,Ladies Finger,1400,14,3,1200,250,False,250

In [3]:
# converting to UTF-8

df.to_csv('../data/zepto_raw_data.csv', index=False, encoding='utf-8')

In [4]:
# re-reading data

df = pd.read_csv("../data/zepto_raw_data.csv")

df.head()

,Category,name,mrp,discountPercent,availableQuantity,discountedSellingPrice,weightInGms,outOfStock,quantity
0,Fruits & Vegetables,Onion,2500,16,3,2100,1000,False,1
1,Fruits & Vegetables,Tomato Hybrid,4200,16,3,3500,1000,False,1
2,Fruits & Vegetables,Tender Coconut,5100,15,3,4300,58,False,1
3,Fruits & Vegetables,Coriander Leaves,2000,15,3,1700,100,False,100
4,Fruits & Vegetables,Ladies Finger,1400,14,3,1200,250,False,250

#### EDA

In [5]:
df.shape

(3732, 9)

In [6]:
# basic info

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3732 entries, 0 to 3731
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Category                3732 non-null   str
 1   name                    3732 non-null   str
 2   mrp                     3732 non-null   int64
 3   discountPercent         3732 non-null   int64
 4   availableQuantity       3732 non-null   int64
 5   discountedSellingPrice  3732 non-null   int64
 6   weightInGms             3732 non-null   int64
 7   outOfStock              3732 non-null   bool
 8   quantity                3732 non-null   int64
dtypes: bool(1), int64(6), str(2)
memory usage: 237.0 KB

In [7]:
df.columns

Index(['Category', 'name', 'mrp', 'discountPercent', 'availableQuantity',
       'discountedSellingPrice', 'weightInGms', 'outOfStock', 'quantity'],
      dtype='str')

In [8]:
# checking for null

df.isna().sum()

Category                  0
name                      0
mrp                       0
discountPercent           0
availableQuantity         0
discountedSellingPrice    0
weightInGms               0
outOfStock                0
quantity                  0
dtype: int64

In [9]:
# checking for duplicates

df.duplicated().sum()

np.int64(2)

In [10]:
# dropping duplicates

df.drop_duplicates(inplace=True)

In [11]:
# re-checking for duplicates

df.duplicated().sum()

np.int64(0)

In [12]:
df.shape

(3730, 9)

In [13]:
# snake casing column names

df = df.rename(columns={'Category' : 'category','discountPercent':'discount_pct', 'availableQuantity' : 'available_qnt',
       'discountedSellingPrice' : 'discounted_selling_price', 'weightInGms' : 'weight_in_gms', 'outOfStock' : 'out_of_stock'})

df.columns

Index(['category', 'name', 'mrp', 'discount_pct', 'available_qnt',
       'discounted_selling_price', 'weight_in_gms', 'out_of_stock',
       'quantity'],
      dtype='str')

In [14]:
# listing categories

sorted(df['category'].unique())

['Beverages',
 'Biscuits',
 'Chocolates & Candies',
 'Cooking Essentials',
 'Dairy, Bread & Batter',
 'Fruits & Vegetables',
 'Health & Hygiene',
 'Home & Cleaning',
 'Ice Cream & Desserts',
 'Meats, Fish & Eggs',
 'Munchies',
 'Paan Corner',
 'Packaged Food',
 'Personal Care']

In [15]:
# out of stock count

df['out_of_stock'].value_counts()

out_of_stock
False    3277
True      453
Name: count, dtype: int64

In [16]:
# sku count

pd.DataFrame(df['name'].value_counts().sort_values(ascending=False))

                                                   count
name
Arden Eggs White                                      10
Quaker Oats                                           10
Sunfeast Yippee! Pasta Treat - Sour Cream Onion       10
Mother's Recipe Tamarind Paste                        10
Amul Delicious Fat Spread - Cholesterol Free          10
...                                                  ...
Parle Rusk Elaichi                                     1
Britannia Treat Creme Wafers - Vanilla                 1
Dukes Sour & Cream Onion Nibbles Baked                 1
Unibic SugarFree - Butter Cookies                      1
Dabur Honitus Herbal Cough Remedy Ayurvedic Syrup      1

[1681 rows x 1 columns]

#### Data Cleaning

In [17]:
# products with mrp=0

df[df['mrp']==0]

,category,name,mrp,discount_pct,available_qnt,discounted_selling_price,weight_in_gms,out_of_stock,quantity
3606,Home & Cleaning,Cherry Blossom Liquid Shoe Polish Neutral,0,0,1,0,75,False,75

In [18]:
df['mrp'].head()

0    2500
1    4200
2    5100
3    2000
4    1400
Name: mrp, dtype: int64

In [19]:
# mrp from paise to rupees

df['mrp'] = df['mrp']/100

df['mrp'].head()

0    25.0
1    42.0
2    51.0
3    20.0
4    14.0
Name: mrp, dtype: float64

In [20]:
df['discounted_selling_price'].head()

0    2100
1    3500
2    4300
3    1700
4    1200
Name: discounted_selling_price, dtype: int64

In [21]:
# mrp from paise to rupees

df['discounted_selling_price'] = df['discounted_selling_price']/100

df['discounted_selling_price'].head()

0    21.0
1    35.0
2    43.0
3    17.0
4    12.0
Name: discounted_selling_price, dtype: float64

In [22]:
# saving clead dataset as .csv

df.to_csv("../data/zepto_cleaned.csv",index=False)

In [28]:
df[df['mrp']<df['mrp'].max()].sort_values(by='mrp', ascending=False)

,category,name,mrp,discount_pct,available_qnt,discounted_selling_price,weight_in_gms,out_of_stock,quantity
3016,Personal Care,Pampers Pants - Large,1549.0,45,3,849.0,82,False,82
3360,Paan Corner,Pampers Pants - Large,1549.0,45,3,849.0,82,False,82
363,Cooking Essentials,Praakritik Natural Desi Gir Cow A2 Ghee,1450.0,10,6,1305.0,540,False,540
877,Munchies,Praakritik Natural Desi Gir Cow A2 Ghee,1450.0,10,6,1305.0,540,False,540
635,Munchies,Dhara Kachi Ghani Mustard Oil Jar,1250.0,8,6,1143.0,5000,False,5
...,...,...,...,...,...,...,...,...,...
2734,Biscuits,Britannia Roll Yo! Strawberry Swiss Roll,10.0,0,0,10.0,28,True,28
780,Munchies,Ching's Chicken Chilli Masala,10.0,0,6,10.0,20,False,20
1805,Ice Cream & Desserts,Chings Instant Soup - Sweet Corn Veg,10.0,0,2,10.0,15,False,15
567,Cooking Essentials,Ching's Chow Mein Hakka Noodles Masala,10.0,0,0,10.0,20,True,20
3606,Home & Cleaning,Cherry Blossom Liquid Shoe Polish Neutral,0.0,0,1,0.0,75,False,75

In [26]:
df[df['mrp']<df['mrp'].max()]

,category,name,mrp,discount_pct,available_qnt,discounted_selling_price,weight_in_gms,out_of_stock,quantity
0,Fruits & Vegetables,Onion,25.0,16,3,21.0,1000,False,1
1,Fruits & Vegetables,Tomato Hybrid,42.0,16,3,35.0,1000,False,1
2,Fruits & Vegetables,Tender Coconut,51.0,15,3,43.0,58,False,1
3,Fruits & Vegetables,Coriander Leaves,20.0,15,3,17.0,100,False,100
4,Fruits & Vegetables,Ladies Finger,14.0,14,3,12.0,250,False,250
...,...,...,...,...,...,...,...,...,...
3727,Health & Hygiene,Stayfree Secure Dry Cover Extra Large Sanitary...,42.0,2,0,41.0,406,True,7
3728,Health & Hygiene,Dabur Honitus Herbal Cough Remedy Ayurvedic Syrup,105.0,15,0,89.0,100,True,100
3729,Health & Hygiene,Whisper Bindazzz Night Sanitary Pads XL Plus,185.0,0,0,185.0,870,True,15
3730,Health & Hygiene,Fine Life Cotton Balls,60.0,0,0,60.0,50,True,50
3731,Health & Hygiene,Dettol Antiseptic Liquid,30.0,0,0,30.0,60,True,60